# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0e5a95f16afbfd91c1ab069efdc62f3ca1063adf12685e9bd91ccbb94f109a9ad8aaf82611ac50647801de189c4f1384f11a8330c1d575a5dafb76d09ef06eb

test:
  secret_key_base: e8cd3d43960d75cbbaeb9c2cc99d63b7a1b379d0c396197e4d242b46b93de41710c4919faa894dbe76587daec47b7622d28525024211f4869f125b7f5b08709e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
